name: auto_get_hot

on:
  create
  # schedule:
    # - cron: "30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run .py
      run: python hot_to_md.py
